# Site settings
title: RESTEasy
email: jperkins@redhat.com
url: "https://resteasy.dev"
description: "RESTEasy is a fully certified and portable implementation of the Jakarta RESTful Web Services specification"
meta_author: RESTEasy
# Build settings
markdown: kramdown
parse_block_html: true
permalink: pretty
exclude:
  - "less"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"

gems:
  - jekyll-paginate
  - jekyll-feed
plugins:
  - jekyll-paginate

# Pagination
paginate: 15
paginate_path: "blogs/page:num"
